Skip cleanup
Problem:
```
Error: Cannot find module 'adm-zip'
```

Solution: I believe this is caused by cleanup called before deploying,
so it just deleted most of the files produced during the build. Even
if that is not the case, we still want to skip cleanup as we're
uploading build artifacts.